name: Bug 报告
description: 报告工具的问题或错误
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你花时间报告 Bug！请尽可能详细地描述问题。

  - type: input
    id: tool
    attributes:
      label: 相关工具
      description: 哪个工具出现了问题？
      placeholder: "例如：JSON 格式化、时间戳转换"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请清晰描述遇到的问题
      placeholder: 描述你遇到的问题...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: 如何复现这个问题？
      placeholder: |
        1. 打开 '...'
        2. 输入 '...'
        3. 点击 '...'
        4. 看到错误
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望行为
      description: 你期望发生什么？
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 浏览器
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - 其他
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: 操作系统
      placeholder: "例如：Windows 11, macOS 14, Ubuntu 22.04"

  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果有的话，请添加截图帮助说明问题

  - type: textarea
    id: additional
    attributes:
      label: 其他信息
      description: 任何其他可能有用的信息
