name: 功能请求
description: 建议新工具或新功能
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！我们很乐意听取你的想法。

  - type: dropdown
    id: type
    attributes:
      label: 请求类型
      options:
        - 新工具
        - 现有工具改进
        - 界面/体验优化
        - 其他
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 请描述你希望添加的功能
      placeholder: 清晰描述这个功能...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解决的问题
      description: 这个功能解决什么问题？
      placeholder: 我在 [...] 时遇到困难...

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 你有什么实现想法吗？

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你考虑过其他方案吗？

  - type: textarea
    id: references
    attributes:
      label: 参考
      description: 类似工具或参考链接（可选）
      placeholder: |
        - https://example.com
        - 类似工具：xxx

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿
      options:
        - label: 我愿意帮忙实现这个功能
