name: 新工具提议
description: 提议添加新的在线工具
title: "[Tool] "
labels: ["new-tool"]
body:
  - type: markdown
    attributes:
      value: |
        有好的工具想法？太棒了！请告诉我们你想要什么工具。

  - type: input
    id: tool_name
    attributes:
      label: 工具名称
      placeholder: "例如：Markdown 编辑器"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 工具分类
      options:
        - 开发工具 (dev)
        - 文本工具 (text)
        - 时间工具 (time)
        - 生成器 (generator)
        - 媒体工具 (media)
        - 计算器 (calculator)
        - 转换器 (converter)
        - 提取器 (extractor)
        - AI 工具 (ai)
        - 网络工具 (network)
        - SEO 工具 (seo)
        - 安全工具 (security)
        - 新分类
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 工具描述
      description: 这个工具做什么？
      placeholder: 描述工具的功能和用途...
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: 核心功能
      description: 列出工具应有的主要功能
      placeholder: |
        - 功能 1
        - 功能 2
        - 功能 3
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: 使用场景
      description: 什么情况下会用到这个工具？
      placeholder: |
        - 场景 1：...
        - 场景 2：...

  - type: textarea
    id: references
    attributes:
      label: 参考实现
      description: 类似工具或参考链接（可选）

  - type: checkboxes
    id: requirements
    attributes:
      label: 技术要求
      description: 这个工具需要：
      options:
        - label: 可以纯前端实现（无需后端）
        - label: 数据可以完全在本地处理
        - label: 可以离线使用

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿
      options:
        - label: 我愿意帮忙开发这个工具
